export const ICON_NAMES: readonly string[] = [
  '777',
  'alien',
  'apito',
  'aposta',
  'basquete',
  'bola-8',
  'campo-de-futebol',
  'carta-de-baralho',
  'cartas',
  'chama-curva',
  'chama',
  'controle-de-videogame',
  'coroa',
  'dado',
  'diamante',
  'espada',
  'estrela',
  'estrelas',
  'ficha-de-poker',
  'futebol',
  'gameboy',
  'joystick',
  'mao-do-rock',
  'maquina-de-caca-niqueis',
  'peça-de-quebra-cabeças',
  'peça-de-xadre-rei',
  'podio',
  'porquinho',
  'saco-de-moedas',
  'tenis',
  'trevo',
  'trofeu',
  'volei',
] as const;

export function getIconUrl(name: string): string {
  return `/assets/icons/${name}.svg`;
}
